services:
  # Eureka Server
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  # MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices-network

  # MySQL
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: todoapp
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: userdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


    networks:
      - microservices-network
    command: --default-authentication-plugin=mysql_native_password

  # Task Service
  task-service:
    build: ./task-service
    depends_on:
      - eureka-server
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=taskdb
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin
    ports:
      - "8081:8081"
    networks:
      - microservices-network

  # User Service
  user-service:
    build: ./user-service
    depends_on:
      - eureka-server
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/userdb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=todoapp
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDLAUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin
    ports:
      - "8082:8082"
    networks:
      - microservices-network

  # List Service
  list-service:
    build: ./list-service
    depends_on:
      - eureka-server
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/listdb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=todoapp
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDLAUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin
    ports:
      - "8083:8083"
    networks:
      - microservices-network

  # API Gateway
  api-gateway:
    build: ./api-gateway
    depends_on:
      - eureka-server
      - task-service
      - user-service
      - list-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
      - SPRING_CLOUD_GATEWAY_GLOBALCORS_CORSCONFIGURATION_[/**]_ALLOWEDORIGINS=http://localhost:3000,http://localhost
      - SPRING_CLOUD_GATEWAY_GLOBALCORS_CORSCONFIGURATION_[/**]_ALLOWEDMETHODS=GET,POST,PUT,DELETE,OPTIONS
      - SPRING_CLOUD_GATEWAY_GLOBALCORS_CORSCONFIGURATION_[/**]_ALLOWEDHEADERS=*
      - SPRING_CLOUD_GATEWAY_GLOBALCORS_CORSCONFIGURATION_[/**]_ALLOWCREDENTIALS=true
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin
    ports:
      - "8080:8080"
    networks:
      - microservices-network

  # Frontend
  frontend:
    build: ./todo-frontend
    ports:
      - "80:80"
      - "3000:3000"  # Ajout du port 3000 pour dev
    depends_on:
      - api-gateway
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  mongodb_data:
  mysql_data: