apiVersion: apps/v1
kind: Deployment
metadata:
  name: list-service
  labels:
    app: list-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: list-service
  template:
    metadata:
      labels:
        app: list-service
    spec:
      containers:
      - name: list-service
        image: todoapp/list-service:latest
        imagePullPolicy: Never
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://mysql:3306/listdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
          - name: SPRING_DATASOURCE_USERNAME
            value: "todoapp"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "password"
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: http://eureka-server:8761/eureka/
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: list-service
spec:
  selector:
    app: list-service
  ports:
  - port: 8083
    targetPort: 8083